### ISSUE TITLE
我在vue中打包时报错  不支持es6语法 

### ISSUE THREAD

**Issue by zhangchenpan** [alexlees/directive-photoswipe#1]
![image](https://user-images.githubusercontent.com/33886465/42506149-9b4c6238-8473-11e8-81ad-f6d5542cf8a2.png)

**Comment by alexlees** [comment]
我在本地测试 能正确打包 你尝试更新directive-photoswipe到0.0.3再试试

**Comment by zhangchenpan** [comment]
请问 0.0.3版本发布了吗?我看git上您的版本还在0.0.2
